### ISSUE TITLE
Build Error on VS 22 

### ISSUE THREAD

**Issue by amit-xai** [Cipher7/ChaiLdr#1]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB4036	The "MASM" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64" directory.	ChaiLdr	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\masm.targets	70

**Comment by Cipher7** [comment]
Right-click on the project in VS, go to "Build Customizations -> tick the masm box" . Then right click on the .asm file and go to Settings-> Drop down box -> Microsoft Macro Assembler" . This should get the asm to be included into the project.

**Comment by amit-xai** [comment]
<img width="509" alt="image" src="https://github.com/Cipher7/ChaiLdr/assets/66508064/3aaaf219-1c89-44da-9d4b-4bd7409534bc">
Already did , tried solutions from github etc
it is not working somehow

**Comment by Cipher7** [comment]
Change the option to Release and try again, also I have pushed some other fixes , pls clone the repo again and try. Do not compile in Debug, compile as Release x64
