### ISSUE TITLE
NtAllocateVirtualMemory - Failed With Error 0x000000D

### ISSUE THREAD

**Issue by Cyb3rN3rd777** [Cipher7/ChaiLdr#3]
Hello, 

i tried to compile it with Release and seems to work until running it, 

could it be because i am using a local server? 

<img width="522" alt="Screenshot 2024-04-08 at 2 31 44 PM" src="https://github.com/Cipher7/ChaiLdr/assets/144471817/74682462-b558-4b6b-bc36-8e8307272cbc">

Error :

<img width="800" alt="Screenshot 2024-04-08 at 2 39 13 PM" src="https://github.com/Cipher7/ChaiLdr/assets/144471817/e821d559-2153-4aae-b293-04a817ab5d61">

Thanks,

**Comment by Cipher7** [comment]
Don't specify a port explicitly, I have given options for HTTP which uses 80, or HTTPS which uses 443, these are the ports that are passed to the downloader as per your specification. Only put in the IP address

![image](https://github.com/Cipher7/ChaiLdr/assets/70212373/5bfa3da2-846a-4a10-986c-b238883c46a5)

The highlighted option selects if you want HTTPS or not, if TRUE => port 443 , if FALSE => port 80

NOTE : If you are using HTTPS, then make sure your server supports it along with the proper SSL certs etc

**Comment by Cyb3rN3rd777** [comment]
Amazing, it worked. Thanks
